{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "blob-indexer.fullname" . }}-postgres-ingress
  labels:
    {{- include "blob-indexer.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "blob-indexer.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.dbPort }}
{{- end }}
