// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/a-thomas-22/blob-indexer-api",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/blob/latest": {
            "get": {
                "description": "Retrieve the latest confirmed blob transactions from the blockchain",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "blobs"
                ],
                "summary": "Get latest confirmed blobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Network name or chain ID (default: first enabled network)",
                        "name": "network",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of blobs to return (default: 10, max: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of blobs to skip for pagination (default: 0, max: 10000)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by sender address",
                        "name": "from",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.BlobResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/blob/mempool": {
            "get": {
                "description": "Retrieve pending blob transactions from the mempool",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "blobs"
                ],
                "summary": "Get pending blobs from mempool",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Network name or chain ID (default: first enabled network)",
                        "name": "network",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of blobs to return (default: 10, max: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of blobs to skip for pagination (default: 0, max: 10000)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by sender address",
                        "name": "from",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.BlobResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/blob/pricing": {
            "get": {
                "description": "Retrieve current and historical blob pricing with utilization metrics and fork parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "blobs"
                ],
                "summary": "Get blob pricing data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Network name or chain ID (default: first enabled network)",
                        "name": "network",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of recent blocks to include (default: 20, max: 100)",
                        "name": "blocks",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.PricingResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/blob/{txHash}": {
            "get": {
                "description": "Retrieve a specific blob transaction by its hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "blobs"
                ],
                "summary": "Get blob by transaction hash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Network name or chain ID (default: first enabled network)",
                        "name": "network",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Transaction hash",
                        "name": "txHash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.BlobResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "404": {
                        "description": "Blob not found",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/dev/dashboard": {
            "get": {
                "description": "Access the development dashboard",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dev"
                ],
                "summary": "Development dashboard",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/dev/database": {
            "get": {
                "description": "Retrieve statistics about the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dev"
                ],
                "summary": "Get database statistics",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.DatabaseStats"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/dev/indexers": {
            "get": {
                "description": "Retrieve detailed metrics for all indexers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dev"
                ],
                "summary": "Get indexer metrics",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.IndexerMetrics"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/dev/logs": {
            "get": {
                "description": "Retrieve recent application logs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dev"
                ],
                "summary": "Get recent logs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of logs to return (default: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by log level (info, warn, error, debug)",
                        "name": "level",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.LogEntry"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/dev/metrics": {
            "get": {
                "description": "Retrieve system-wide metrics including memory usage, goroutine count, etc.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dev"
                ],
                "summary": "Get system metrics",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.SystemMetrics"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/dev/queries": {
            "get": {
                "description": "Retrieve statistics about database queries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dev"
                ],
                "summary": "Get database query statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of queries to return (default: 20)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.QueryStat"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "Retrieve statistics about blob transactions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get blob statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Network name or chain ID (default: first enabled network)",
                        "name": "network",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.StatsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/stats/windows": {
            "get": {
                "description": "Retrieve rolling time-window statistics for blob market dashboards",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get rolling blob market statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Network name or chain ID (default: first enabled network)",
                        "name": "network",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated rolling windows using m/h/d units (default: 5m,1h,24h,7d; max 8 windows, max 30d each)",
                        "name": "windows",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.RollingStatsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Retrieve the current status of the indexer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Get indexer status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Network name or chain ID (default: first enabled network)",
                        "name": "network",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.StatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Retrieve the top users of blob transactions by count",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get top blob users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Network name or chain ID (default: first enabled network)",
                        "name": "network",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of users to return (default: 10, max: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of users to skip for pagination (default: 0, max: 10000)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.UserResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/users/{address}": {
            "get": {
                "description": "Retrieve aggregated blob statistics for a specific sender address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Network name or chain ID (default: first enabled network)",
                        "name": "network",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Ethereum address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.BlobParamsResponse": {
            "type": "object",
            "properties": {
                "max": {
                    "type": "integer"
                },
                "max_gas": {
                    "type": "integer"
                },
                "target": {
                    "type": "integer"
                },
                "target_gas": {
                    "type": "integer"
                },
                "update_fraction": {
                    "type": "integer"
                }
            }
        },
        "api.BlobResponse": {
            "type": "object",
            "properties": {
                "base_fee_per_blob_gas": {
                    "type": "string"
                },
                "blob_gas_used": {
                    "type": "integer"
                },
                "blob_index": {
                    "type": "integer"
                },
                "blob_size_bytes": {
                    "type": "integer"
                },
                "block_number": {
                    "type": "integer"
                },
                "confirmed": {
                    "type": "boolean"
                },
                "fee_cap_headroom_percent": {
                    "type": "string"
                },
                "fee_cap_headroom_wei": {
                    "type": "string"
                },
                "from_address": {
                    "type": "string"
                },
                "max_cost_wei": {
                    "type": "string"
                },
                "max_fee_per_blob_gas": {
                    "type": "string"
                },
                "network_id": {
                    "type": "integer"
                },
                "network_name": {
                    "type": "string"
                },
                "realized_cost_wei": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "tip_per_blob_gas": {
                    "type": "string"
                },
                "total_cost_eth": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                },
                "user_attribution": {
                    "type": "string"
                }
            }
        },
        "api.BlockPricingResponse": {
            "type": "object",
            "properties": {
                "available_blobs": {
                    "type": "integer"
                },
                "blob_base_fee": {
                    "type": "string"
                },
                "blob_count": {
                    "type": "integer"
                },
                "blob_gas_limit": {
                    "type": "integer"
                },
                "blob_gas_target": {
                    "type": "integer"
                },
                "blob_gas_used": {
                    "type": "integer"
                },
                "blob_params_max": {
                    "type": "integer"
                },
                "blob_params_target": {
                    "type": "integer"
                },
                "block_number": {
                    "type": "integer"
                },
                "block_timestamp": {
                    "type": "string"
                },
                "excess_blob_gas": {
                    "type": "integer"
                },
                "is_above_target": {
                    "type": "boolean"
                },
                "is_full": {
                    "type": "boolean"
                },
                "max_blobs": {
                    "type": "integer"
                },
                "target_blobs": {
                    "type": "integer"
                },
                "update_fraction": {
                    "type": "integer"
                },
                "utilization_percent": {
                    "type": "number"
                },
                "utilization_ratio": {
                    "type": "string"
                }
            }
        },
        "api.DatabaseStats": {
            "type": "object",
            "properties": {
                "connection_count": {
                    "type": "integer"
                },
                "idle_connections": {
                    "type": "integer"
                },
                "in_use_connections": {
                    "type": "integer"
                },
                "last_migration_time": {
                    "type": "string"
                },
                "max_open_connections": {
                    "type": "integer"
                },
                "table_stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.TableStat"
                    }
                },
                "total_size": {
                    "type": "string"
                },
                "total_tables": {
                    "type": "integer"
                }
            }
        },
        "api.FeeEstimateRangeResponse": {
            "type": "object",
            "properties": {
                "high": {
                    "type": "string"
                },
                "low": {
                    "type": "string"
                }
            }
        },
        "api.IndexerMetrics": {
            "type": "object",
            "properties": {
                "confirmed_blobs_count": {
                    "type": "integer"
                },
                "last_indexed_block": {
                    "type": "integer"
                },
                "last_indexed_time": {
                    "type": "string"
                },
                "network_id": {
                    "type": "integer"
                },
                "network_name": {
                    "type": "string"
                },
                "pending_blobs_count": {
                    "type": "integer"
                },
                "total_blobs_indexed": {
                    "type": "integer"
                }
            }
        },
        "api.LogEntry": {
            "type": "object",
            "properties": {
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "level": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "api.MarketPressureResponse": {
            "type": "object",
            "properties": {
                "consecutive_full_blocks": {
                    "type": "integer"
                },
                "next_block_fee_estimate": {
                    "$ref": "#/definitions/api.FeeEstimateRangeResponse"
                },
                "percent_recent_blocks_at_max_blobs": {
                    "type": "number"
                },
                "predicted_direction": {
                    "type": "string"
                },
                "recent_blocks_above_target": {
                    "type": "integer"
                }
            }
        },
        "api.PricingResponse": {
            "type": "object",
            "properties": {
                "blob_params": {
                    "$ref": "#/definitions/api.BlobParamsResponse"
                },
                "current_base_fee": {
                    "type": "string"
                },
                "current_excess_gas": {
                    "type": "integer"
                },
                "current_utilization": {
                    "type": "string"
                },
                "fork_stage": {
                    "type": "string"
                },
                "market_pressure": {
                    "$ref": "#/definitions/api.MarketPressureResponse"
                },
                "network_id": {
                    "type": "integer"
                },
                "network_name": {
                    "type": "string"
                },
                "predicted_next_fee": {
                    "type": "string"
                },
                "recent_blocks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.BlockPricingResponse"
                    }
                }
            }
        },
        "api.QueryStat": {
            "type": "object",
            "properties": {
                "calls": {
                    "type": "integer"
                },
                "execution_time": {
                    "type": "number"
                },
                "last_executed": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                },
                "rows_returned": {
                    "type": "integer"
                }
            }
        },
        "api.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "api.RollingStatsResponse": {
            "type": "object",
            "properties": {
                "generated_at": {
                    "type": "string"
                },
                "network_id": {
                    "type": "integer"
                },
                "network_name": {
                    "type": "string"
                },
                "windows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.RollingWindowStats"
                    }
                }
            }
        },
        "api.RollingWindowStats": {
            "type": "object",
            "properties": {
                "average_blob_base_fee": {
                    "type": "string"
                },
                "average_utilization": {
                    "type": "string"
                },
                "duration_seconds": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "median_blob_base_fee": {
                    "type": "string"
                },
                "p95_blob_base_fee": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "total_blob_gas_used": {
                    "type": "integer"
                },
                "total_blobs": {
                    "type": "integer"
                },
                "total_cost_eth": {
                    "type": "string"
                },
                "unique_senders": {
                    "type": "integer"
                },
                "window": {
                    "type": "string"
                }
            }
        },
        "api.StatsResponse": {
            "type": "object",
            "properties": {
                "average_base_fee": {
                    "type": "string"
                },
                "average_tip": {
                    "type": "string"
                },
                "average_total_cost": {
                    "type": "string"
                },
                "last_indexed_block": {
                    "type": "integer"
                },
                "last_indexed_time": {
                    "type": "string"
                },
                "network_id": {
                    "type": "integer"
                },
                "network_name": {
                    "type": "string"
                },
                "total_blobs": {
                    "type": "integer"
                },
                "total_confirmed_blobs": {
                    "type": "integer"
                },
                "total_pending_blobs": {
                    "type": "integer"
                }
            }
        },
        "api.StatusResponse": {
            "type": "object",
            "properties": {
                "indexer_version": {
                    "type": "string"
                },
                "last_indexed_block": {
                    "type": "integer"
                },
                "last_indexed_time": {
                    "type": "string"
                },
                "network_id": {
                    "type": "integer"
                },
                "network_name": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                }
            }
        },
        "api.SystemMetrics": {
            "type": "object",
            "properties": {
                "active_requests": {
                    "type": "integer"
                },
                "architecture": {
                    "type": "string"
                },
                "current_time": {
                    "type": "string"
                },
                "go_version": {
                    "type": "string"
                },
                "memory_usage": {
                    "type": "string"
                },
                "num_cpu": {
                    "type": "integer"
                },
                "num_goroutine": {
                    "type": "integer"
                },
                "operating_system": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "total_requests": {
                    "type": "integer"
                },
                "uptime": {
                    "type": "string"
                }
            }
        },
        "api.TableStat": {
            "type": "object",
            "properties": {
                "index_count": {
                    "type": "integer"
                },
                "last_vacuumed": {
                    "type": "string"
                },
                "row_count": {
                    "type": "integer"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "table_name": {
                    "type": "string"
                }
            }
        },
        "api.UserResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "blob_count": {
                    "type": "integer"
                },
                "last_timestamp": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "network_id": {
                    "type": "integer"
                },
                "network_name": {
                    "type": "string"
                },
                "total_cost_eth": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Network-related endpoints",
            "name": "networks"
        },
        {
            "description": "Blob transaction endpoints",
            "name": "blobs"
        },
        {
            "description": "User attribution endpoints",
            "name": "users"
        },
        {
            "description": "Statistics endpoints",
            "name": "stats"
        },
        {
            "description": "Indexer status endpoints",
            "name": "status"
        },
        {
            "description": "Development endpoints (only available in dev mode)",
            "name": "dev"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Blob Indexer API",
	Description:      "API for indexing and querying blob transactions on Ethereum across multiple networks",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
